---
- name: overwrite sources.list
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    mode: 0644

- name: copy apt key
  copy:
    src: apt.key
    dest: /srv/apt.key

- name: add apt key
  apt_key:
    file: /srv/apt.key
    state: present

- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install aptitude
  apt:
    name: aptitude
    state: latest

- name: apt upgrade
  apt:
    upgrade: safe

