---
# ansible-playbook -i inventory -l dgx site.yml

# Install ansible python dependency on Ubuntu 16.04
- hosts: all
  become: yes
  become_method: sudo
  remote_user: "{{ user }}"
  gather_facts: no
  roles:
    - bootstrap

- hosts: dgx
  become: yes
  become_method: sudo
  remote_user: "{{ user }}"
  roles:
    - default_sw
    - { role: ntp, tags: ntp }
    - role: community/ryanolson.docker
      ansible_user_id: "{{ user }}"
  tasks:
  - name: modify default user
    user:
      name: "{{ user}}"
      groups: docker
      append: yes
    tags:
      - user
  - name: change permissions on /raid
    file:
      path: /raid
      state: directory
      owner: root
      group: root
      mode: "1777"
    tags:
      - raid
      - storage
