---
# ansible-playbook -i inventory slurm.yml

- hosts: slurm-masters
  become: yes
  roles:
    - { role: slurm, is_controller: yes }

- hosts: slurm-compute-nodes
  become: yes
  roles:
    - { role: slurm, is_compute: yes }
