---
# ansible-playbook -i inventory -l dgx software.yml

- hosts: all
  become: true
  tasks:
    - name: upgrade installed packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: safe

- hosts: dgx-servers
  become: yes
  roles:
    - nvidia-docker2
    - dgx-software
    - cachefilesd
  tasks:
  - name: change permissions on /raid
    file:
      path: /raid
      state: directory
      owner: root
      group: root
      mode: "1777"
    tags:
      - raid
      - storage

- hosts: tesla-servers
  become: yes
  roles:
    - nvidia-docker2
    - tesla-software

- hosts: all
  become: true
  roles:
    - nvidia-docker2
    - singularity
  tasks:
  - name: modify default user
    user:
      name: "{{ user }}"
      groups: docker
      append: yes
    tags:
      - user

- hosts: all
  become: true
  roles:
    - reboot
  tasks:
  - name: clean up packages
    apt:
      autoremove: yes
