---
- name: update grub
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX="
    line: 'GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"'
  notify:
    - update grub
    - reboot

- name: create slurm directories
  file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    mode: 0755
  with_items:
    - /etc/slurm
    - /var/log/slurm
    - /var/spool/slurm/d

- name: copy slurmdbd service file
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - slurmd.service

- name: copy configuration files
  template:
    src: "{{ item }}"
    dest: "/etc/slurm/{{ item }}"
  with_items:
    - slurm.conf
    - cgroup.conf
    - gres.conf
  notify:
    - restart slurmd

- name: start slurmd
  systemd:
    name: slurmd
    state: started
    enabled: yes
    daemon-reload: yes
