
- include: munge.yml

- name: install slurm
  apt:
    name: slurm
    state: latest

- name: create slurm user
  user:
    name: slurm
    state: present
    system: yes
    uid: "{{ slurm_user_uid }}"

- include: controller.yml
  when: is_controller

- include: compute.yml
  when: is_compute

# unplug the drain - sometimes nodes get stuck
# sudo scontrol update node=XXX state=idle
# where XXX are the nodes that have changed and are marked as *down*
