---
# - name: overwrite sources.list
#   template:
#     src: sources.list.j2
#     dest: /etc/apt/sources.list
#     owner: root
#     mode: 0644
#
# - name: apt update
#   apt:
#     update_cache: yes
#     cache_valid_time: 3600
#
# - name: install aptitude
#   apt:
#     name: aptitude
#     state: latest
#
# - name: apt upgrade
#   apt:
#     upgrade: safe

- name: install default software
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ default_ubuntu_packages }}"
  tags:
    - packages

- name: install smart monitoring tools
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - lshw
    - smartmontools
  tags:
    - packages

- name: install nvidia drivers and datacenter manager
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - cuda-drivers
    - cuda-drivers-diagnostic 
    - datacenter-gpu-manager 
    - nvidia-sysinfo-dgx
  tags:
    - packages

- name: install nvidia peer memory
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nvidia-peer-memory 
    - nvidia-peer-memory-dkms
  tags:
    - packages

