---
- name: nfs | ensure mountpoint exists
  file: path={{ item.mountpoint }} state=directory
  with_items: '{{ nfs_mounts }}'
  when: nfs_mounts is defined
  tags:
    - nfs

- name: nfs | configure /etc/fstab on clients
  mount:
    name: "{{ item.mountpoint}}"
    src: "{{ item.server | groups['head'][0] }}:{{ item.path }}"
    opts: "{{ item.options }}"
    fstype: nfs 
    state: mounted
  with_items: '{{ nfs_mounts }}'
  when: nfs_mounts is defined
  tags:
    - nfs
