---
- name: restart munge
  service:
    name: munge
    state: restarted

- name: restart slurmd
  service:
    name: slurmd
    state: restarted

- name: restart slurmdbd
  service:
    name: slurmdbd
    state: restarted

- name: restart slurmctld
  service:
    name: slurmctld
    state: restarted

