- name: create user accounts
  user:
    name: "{{ item.username }}"
    state: "{{ item.state | default('present') }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    groups: "{{ item.groups }}"
    remove: yes
    generate_ssh_key: yes
  when: item.username is defined
  with_items:
    - "{{ user_list }}"

- name: set ssh auth keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file', '/home/' + item.username + '/.ssh/id_rsa.pub') }}"
  when: item.username is defined
  with_items:
    - "{{ user_list }}"
