---
- name: install docker-ce
  apt:
    name: docker-ce
    state: latest

- name: update daemon.json configuration
  template:
    src: daemon.j2
    dest: /etc/docker/daemon.json
    owner: root
    mode: 0644
  notify:
    - restart docker

- meta: flush_handlers
