slurm_cluster_name: ngc
slurm_username: slurm
slurm_password: ReplaceWithASecurePasswordInTheVault

slurm_db_username: slurm
slurm_db_password: AlsoReplaceWithASecurePasswordInTheVault

is_controller: no
is_compute: no
